project 'AdLimeDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

inhibit_all_warnings!
install!'cocoapods',:deterministic_uuids=>false

target 'AdLimeDemo' do

    use_frameworks!
    
    pod 'Masonry'
    pod 'AdLimeSdk'
#    pod 'AdLimeMediation_GoogleAds'
#    pod 'AdLimeMediation_Amazon'
#    pod 'AdLimeMediation_AppLovin'
#    pod 'AdLimeMediation_AdColony'
#    pod 'AdLimeMediation_AdGeneration'
#    pod 'AdLimeMediation_Facebook'
#    pod 'AdLimeMediation_Five'
#    pod 'AdLimeMediation_DUADPlatform'
#    pod 'AdLimeMediation_Chartboost'
#    pod 'AdLimeMediation_Criteo'
#    pod 'AdLimeMediation_Flurry'
#    pod 'AdLimeMediation_Fyber'
#    pod 'AdLimeMediation_Imobile'
#    pod 'AdLimeMediation_IronSource'
#    pod 'AdLimeMediation_Maio'
#    pod 'AdLimeMediation_MoPub'
#    pod 'AdLimeMediation_Nend'
#    pod 'AdLimeMediation_Tapjoy'
#    pod 'AdLimeMediation_TikTok'
#    pod 'AdLimeMediation_UnityAds'
#    pod 'AdLimeMediation_Vungle'
#    pod 'DIOSDK'
end
