project 'AdLimeDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

inhibit_all_warnings!

target 'AdLimeDemo' do

    use_frameworks!
    
    pod 'Masonry'
    pod 'AdLimeSdk'
    pod 'AdLimeMediation_GoogleAds'
    pod 'AdLimeMediation_Amazon'
    pod 'AdLimeMediation_AppLovin'
    pod 'AdLimeMediation_AdColony'
    pod 'AdLimeMediation_AdGeneration'
    pod 'AdLimeMediation_Facebook'
    pod 'AdLimeMediation_Chartboost'
    pod 'AdLimeMediation_Flurry'
    pod 'AdLimeMediation_IronSource'
    pod 'AdLimeMediation_Maio'
    pod 'AdLimeMediation_Flurry'
    pod 'AdLimeMediation_MoPub'
    pod 'AdLimeMediation_Nend'
    pod 'AdLimeMediation_TikTok'
    pod 'AdLimeMediation_UnityAds'
    pod 'AdLimeMediation_Vungle'
end
